spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ecommerce?createDatabaseIfNotExist=true
    username: root
    password: toor911
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
        hibernate:
          format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    change-log: classpath:db/changelog/changelog.sql
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

jwt:
  secret: FlfL15c4fYsdUgQZyAaygDBEGQ/lMstiJX3CFkbGdYeBgcrWgiOaCq66krb3rqxt2Kh+CFxBTueZN7a/jP1Ly412qOl4TtjQx5Zan6j7tDM5YPg7xfGwtU1P1MbOU8xcALjLPNlx/nrWWHBk0/lhOrnNep9JBDQfUI9v1VPbCkQDdKgoCa5jnuWzRvCUUvyfs7aMANtfa0yl18YX4ZV+oUxjYbGPA9WDuvVcc6Av79K240qo4NL76RIBd5p6Uiqq/QcauDKllf+AVyMy2IWTWMnH+1sL5vRd4nglxQooooAGXHGq9urk56S3vUQkorCPaJF0UnlEn202d6xEFogp
  token-validity-in-seconds: 86400
  token-validity-in-seconds-for-remember-me: 2592000
  